repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
-   repo: https://github.com/PyCQA/bandit
    rev: '1.8.6'
    hooks:
    - id: bandit
      args: ["--exclude", "tests/*"]
-   repo: local
    hooks:
    - id: grep-for-devtools
      name: Check for devtools in fractal_client files
      entry: bash -c 'for file in "$@"; do if grep -n "devtools" "$file"; then echo "$file" && exit 1; fi; done' --
      language: system
      files: fractal_client/
