site_name: Fractal Client

repo_url: https://github.com/fractal-analytics-platform/fractal-client
repo_name: fractal-client

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: true
    toc_depth: 3

theme:
  name: "material"
  logo: 'assets/fractal_logo.png'
  favicon: 'assets/fractal_favicon.png'
  custom_dir: "docs/overrides"
  features:
    - content.code.annotate
    - content.code.copy
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: light blue
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: light blue
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  navigation:
    expand: true


nav:
  - Home page: index.md
  - Install: install.md
  - Version compatibility: versions.md
  - CLI reference: reference/fractal/
  - Development: development.md
  - Changelog: changelog.md

watch:
  - fractal_client

plugins:
  - search
  - autorefs
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: false
            docstring_section_style: "spacy"
            docstring_style: "google"
            show_source: true
            filters: []
            show_root_full_path: false
  - include-markdown

extra_css:
  - extra.css

copyright: |
  © Copyright 2024
  University of Zurich
  (see <u><a href="https://github.com/fractal-analytics-platform/fractal/blob/main/LICENSE">
  LICENSE
  </a></u>).
