name: Build package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@d7fe1a5a186096cccdd5fa2252d223b54fa53a72
        with:
          version: "0.9.7"
          enable-cache: true
      - run: uv build
