name: docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

jobs:

  build:
    name: "Build documentation"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          version: "0.9.24"
          enable-cache: true
      - run: uv sync --frozen --group docs
      - run: uv run --frozen mkdocs build --config-file mkdocs.yml --site-dir site --clean

      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: "site"

  deploy:
    name: "Deploy docs"
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    permissions:
      # https://github.com/actions/deploy-pages?tab=readme-ov-file
      # https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-cloud-providers#adding-permissions-settings
      pages: write  # To create pages deployments when calling the GitHub API
      id-token: write # To request the OIDC JWT token
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
        id: deployment
