name: Publish package to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+[a-c][0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+alpha[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

permissions: {}

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/fractal-client
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@447e6d02b15d65b3247cce2d6019f11957285d11
        with:
          version: "0.9.7"
          enable-cache: false
      - run: uv build --verbose
      - uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247
