name: Publish package to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+[a-c][0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+alpha[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

permissions: {}

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/fractal-client
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: false
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
      - uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@447e6d02b15d65b3247cce2d6019f11957285d11
        with:
          version: "0.9.7"
          enable-cache: false
      - run: uv build --verbose
      - uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b
